partial:
  by: target
version: 2
project_name: opentelemetry-collector-releases
builds:
  - id: otelcol-k8s
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - ppc64le
      - s390x
    dir: _build
    binary: otelcol-k8s
    ldflags:
      - -s
      - -w
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
archives:
  - id: otelcol-k8s
    builds:
      - otelcol-k8s
    name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'
checksum:
  name_template: '{{ .ProjectName }}_otelcol-k8s_checksums.txt'
monorepo:
  tag_prefix: v
