partial:
  by: target
version: 2
project_name: opentelemetry-collector-releases
builds:
  - id: otelcol-contrib
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
      - ppc64le
      - s390x
    goarm:
      - "7"
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: s390x
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: s390x
    dir: _build
    binary: otelcol-contrib
    builder: prebuilt
    prebuilt:
      path: artifacts/otelcol-contrib_{{ .Target }}/otelcol-contrib{{- if eq .Os "windows" }}.exe{{ end }}
archives:
  - id: otelcol-contrib
    builds:
      - otelcol-contrib
    name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'
nfpms:
  - package_name: otelcol-contrib
    contents:
      - src: otelcol-contrib.service
        dst: /lib/systemd/system/otelcol-contrib.service
      - src: otelcol-contrib.conf
        dst: /etc/otelcol-contrib/otelcol-contrib.conf
        type: config|noreplace
      - src: config.yaml
        dst: /etc/otelcol-contrib/config.yaml
        type: config|noreplace
    scripts:
      preinstall: preinstall.sh
      postinstall: postinstall.sh
      preremove: preremove.sh
    overrides:
      rpm:
        dependencies:
          - /bin/sh
    id: otelcol-contrib
    builds:
      - otelcol-contrib
    formats:
      - deb
      - rpm
    maintainer: The OpenTelemetry Collector maintainers <cncf-opentelemetry-maintainers@lists.cncf.io>
    description: OpenTelemetry Collector - otelcol-contrib
    license: Apache 2.0
checksum:
  name_template: '{{ .ProjectName }}_otelcol-contrib_checksums.txt'
monorepo:
  tag_prefix: v
