name: CI - Core - GoReleaser

on:
  merge_group: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-goreleaser:
    name: CI - Core - GoReleaser
    uses: ./.github/workflows/continuous-release.yaml
    with:
      distribution: otelcol
      goos: '[ "linux", "windows", "darwin" ]'
      goarch: '[ "386", "amd64", "arm64", "ppc64le", "arm", "s390x" ]'
    secrets: inherit
