name: Nightly Release

on:
  workflow_dispatch:
  merge_group: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  nightly-release:
    name: CI - Core - GoReleaser
    uses: ./.github/workflows/continuous-release.yaml
    with:
      distribution: otelcol
      goos: '[ "linux" ]'
      goarch: '[ "amd64", "arm64" ]'
    secrets: inherit
