name: Nightly Package Tests - Contrib - GoReleaser

on:
  push:
    branches: [main]
    paths:
      - "distributions/otelcol-contrib/**"
      - "cmd/**"
      - ".github/**"
      - "scripts/**"
      - "Makefile"
      - "go.mod"
      - "go.sum"
  pull_request:
    branches: [main]
    paths:
      - "distributions/otelcol-contrib/**"
      - "cmd/**"
      - ".github/**"
      - "scripts/**"
      - "Makefile"
      - "go.mod"
      - "go.sum"
  schedule:
    - cron: "0 2 * * *" # every day at 2am UTC

jobs:
  check-goreleaser:
    name: Continuous Integration - Contrib - GoReleaser
    uses: ./.github/workflows/base-ci-goreleaser.yaml
    with:
      distribution: otelcol-contrib
      goos: '[ "linux" ]'
      goarch: '[ "amd64" ]'
      latest: true
    secrets: inherit

  package-tests:
    name: Package tests
    needs: check-goreleaser
    uses: ./.github/workflows/package-tests.yaml
    with:
      distribution: otelcol-contrib
      type: '[ "deb", "rpm" ]'
