name: Release OTLP

on:
  push:
    tags: ["v*"]

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      NIGHTLY: ${{ steps.nightly-check.outputs.NIGHTLY }}
    steps:
      - name: Set nightly enabled
        id: nightly-check
        if: contains(github.ref, '-nightly')
        run: |
          echo "NIGHTLY=true" >> "$GITHUB_OUTPUT"
  release:
    name: Release OTLP
    needs: [prepare]
    uses: ./.github/workflows/base-release.yaml
    with:
      distribution: otelcol-otlp
      goos: '[ "linux", "darwin" ]'
      goarch: '[ "386", "amd64", "arm64", "ppc64le", "arm", "s390x" ]'
      nightly: ${{ needs.prepare.outputs.NIGHTLY }}
    secrets: inherit
    permissions: write-all
  release-windows:
    name: Release OTLP (Windows)
    needs: [prepare]
    if: needs.prepare.outputs.NIGHTLY != 'true'
    uses: ./.github/workflows/base-release.yaml
    with:
      distribution: otelcol-otlp
      goos: '[ "windows" ]'
      goarch: '[ "386", "amd64" ]'
      runner_os: windows-2022
    secrets: inherit
    permissions: write-all
